main: Dungeon_Generation.o
	gcc Dungeon_Generation.o -o Dungeon_Generation

Dungeon_Generation.o: Dungeon_Generation.o
	gcc -c Dungeon_Generation.c -Wall -Werror -ggdb -o Dungeon_Generation.o

clean:
	rm -rf *o Dungeon_Generation
