main: DungeonLoadSave.o
	gcc DungeonLoadSave.o -o DungeonLoadSave

DungeonLoadSave.o: DungeonLoadSave.o
	gcc -c DungeonLoadSave.c -Wall -Werror -ggdb -o DungeonLoadSave.o

clean:
	rm -rf *o DungeonLoadSave


